### ISSUE TITLE
Crowdsourcing API keys

### ISSUE THREAD

**Issue by ricklamers** [im-in-space/BirdsiteLive#1]
Hi there. Cool fork.

I haven’t looked at the BirdsiteLive code yet but I was wondering how difficult it would be to allow people to contribute their own API keys such that one BirdsiteLive instance can scale to following more Birdsite users.

There might also be security implications. Are you interested in exploring that angle?

**Comment by mkody** [comment]
Hi!

I'm really not interested into doing that. Sharing API keys between people doesn't sound like a good idea, I feel like you're giving way too much trust to the instance admin that way.

The best option is to host more instances and spread out the load, not only for the calls to Twitter's API but also for the BSL instance itself.
